ALTER TABLE [dbo].[Characteristics]
    ADD CONSTRAINT [PK_Chacteristics] PRIMARY KEY CLUSTERED ([characteristic_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

