ALTER TABLE [dbo].[LogFunctions]
    ADD CONSTRAINT [PK_LogFunctions] PRIMARY KEY CLUSTERED ([logfunction_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

