ALTER TABLE [dbo].[DataTypes]
    ADD CONSTRAINT [PK_DataTypes] PRIMARY KEY CLUSTERED ([datatype_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

